# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFunction = QtWidgets.QMenu(self.menubar)
        self.menuFunction.setObjectName("menuFunction")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionUpdate_log = QtWidgets.QAction(MainWindow)
        self.actionUpdate_log.setObjectName("actionUpdate_log")
        self.actionReport_an_issue = QtWidgets.QAction(MainWindow)
        self.actionReport_an_issue.setObjectName("actionReport_an_issue")
        self.actionReview = QtWidgets.QAction(MainWindow)
        self.actionReview.setObjectName("actionReview")
        self.actionSource_code_GitHub = QtWidgets.QAction(MainWindow)
        self.actionSource_code_GitHub.setObjectName("actionSource_code_GitHub")
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionUpdate_log)
        self.menuHelp.addAction(self.actionReport_an_issue)
        self.menuHelp.addAction(self.actionReview)
        self.menuHelp.addAction(self.actionSource_code_GitHub)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFunction.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuFunction.setTitle(_translate("MainWindow", "Function"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionUpdate_log.setText(_translate("MainWindow", "Update log"))
        self.actionReport_an_issue.setText(_translate("MainWindow", "Report an issue"))
        self.actionReview.setText(_translate("MainWindow", "Review"))
        self.actionSource_code_GitHub.setText(_translate("MainWindow", "Source code(GitHub)"))
