# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.settingsWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.settingsWidget.setObjectName("settingsWidget")
        self.generalSettings = QtWidgets.QWidget()
        self.generalSettings.setObjectName("generalSettings")
        self.formLayout = QtWidgets.QFormLayout(self.generalSettings)
        self.formLayout.setObjectName("formLayout")
        self.streamOption = QtWidgets.QLabel(self.generalSettings)
        self.streamOption.setObjectName("streamOption")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.streamOption)
        self.streamChoice = QtWidgets.QComboBox(self.generalSettings)
        self.streamChoice.setObjectName("streamChoice")
        self.streamChoice.addItem("")
        self.streamChoice.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.streamChoice)
        self.settingsWidget.addTab(self.generalSettings, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.settingsWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.settingsWidget)
        SettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        SettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SettingsWindow)
        self.statusbar.setObjectName("statusbar")
        SettingsWindow.setStatusBar(self.statusbar)
        self.actionExport = QtWidgets.QAction(SettingsWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionImport_configuration = QtWidgets.QAction(SettingsWindow)
        self.actionImport_configuration.setObjectName("actionImport_configuration")
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionImport_configuration)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(SettingsWindow)
        self.settingsWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings"))
        self.streamOption.setText(_translate("SettingsWindow", "Stream response"))
        self.streamChoice.setItemText(0, _translate("SettingsWindow", "Enable"))
        self.streamChoice.setItemText(1, _translate("SettingsWindow", "Disable"))
        self.settingsWidget.setTabText(self.settingsWidget.indexOf(self.generalSettings), _translate("SettingsWindow", "General"))
        self.settingsWidget.setTabText(self.settingsWidget.indexOf(self.tab_2), _translate("SettingsWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("SettingsWindow", "File"))
        self.actionExport.setText(_translate("SettingsWindow", "Export...(&E)"))
        self.actionExport.setToolTip(_translate("SettingsWindow", "Export the current configuration"))
        self.actionImport_configuration.setText(_translate("SettingsWindow", "Import configuration(&I)"))
        self.actionImport_configuration.setToolTip(_translate("SettingsWindow", "Import the configuration file saved before"))
